version: "3"
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/vendor
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    user: root
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx:/etc/nginx/conf.d/
    ports:
      - "3000:80"
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    user: root
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_PASSWORD: 1
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
