export const SET_POSTS = 'SET_POSTS';
export const SET_POSTS_LOADING_STATUS = 'SET_POSTS_LOADING_STATUS';

export const POSTS_FETCHING = 'POSTS_FETCHING';
export const POSTS_LOAD_SUCCESS = 'POSTS_LOAD_SUCCESS';
export const POSTS_LOAD_ERROR = 'POSTS_LOAD_ERROR';
